apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
  name: testsvc3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test2-app
status:
  loadBalancer: {}
